spring:
  cloud:
    gateway:
      routes:
        - id: route0
          uri: http://localhost:8080
          predicates:
            - Path=/enterprise/**
        - id: route1
          uri: http://localhost:8081
          predicates:
            - Path=/employe/**
        - id: route2
          uri: http://localhost:8082
          predicates:
            - Path=/departement/**
        - id: route3
          uri: http://localhost:8083
          predicates:
            - Path=/client/**
        - id: route4
          uri: http://localhost:8084
          predicates:
            - Path=/fournisseur/**
